-- AlterTable
ALTER TABLE "Zone" ADD COLUMN     "capacity" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN     "height" DOUBLE PRECISION NOT NULL DEFAULT 400,
ADD COLUMN     "width" DOUBLE PRECISION NOT NULL DEFAULT 600;
